# 5.1 pandas的数据结构介绍

>  要使用pandas，你首先就得熟悉它的两个主要数据结构：Series和DataFrame。虽然它们并不能解决所有问题，但它们为大多数应用提供了一种可靠的、易于使用的基础。


## Series

> Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成。仅由一组数据即可产生最简单的Series：

In [27]:
import pandas as pd

obj = pd.Series([4, 7, -5, 3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [28]:
obj.values

array([ 4,  7, -5,  3])

In [29]:
obj.index

RangeIndex(start=0, stop=4, step=1)

> 通常，我们希望所创建的Series带有一个可以对各个数据点进行标记的索引：

In [30]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [31]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [32]:
obj2.values

array([ 4,  7, -5,  3])

In [33]:
obj2['a']

-5

In [34]:
obj2['c']

3

> 如果数据被存放在一个Python字典中，也可以直接通过这个字典来创建Series：

In [35]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

> 如果只传入一个字典，则结果Series中的索引就是原字典的键（有序排列）。你可以传入排好序的字典的键以改变顺序：

In [36]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index=states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [39]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [40]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

> Series对象本身及其索引都有一个name属性，该属性跟pandas其他的关键功能关系非常密切：

In [41]:
obj4.name = 'population'

obj4.index.name = 'state'

In [42]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

> Series的索引可以通过赋值的方式就地修改：

In [43]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [44]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

> DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有行索引也有列索引，它可以被看做由Series组成的字典（共用同一个索引）。DataFrame中的数据是以一个或多个二维块存放的（而不是列表、字典或别的一维数据结构）。有关DataFrame内部的技术细节远远超出了本书所讨论的范围。
>
>> 笔记：虽然DataFrame是以二维结构保存数据的，但你仍然可以轻松地将其表示为更高维度的数据（层次化索引的表格型结构，这是pandas中许多高级数据处理功能的关键要素，我们会在第8章讨论这个问题）。
>
> 建DataFrame的办法有很多，最常用的一种是直接传入一个由等长列表或NumPy数组组成的字典：

In [45]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

> 排序

如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列：

In [47]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

> 如果传入的列在数据中找不到，就会在结果中产生缺失值：

In [48]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

> 通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series：

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [58]:
frame2['year']

# frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [60]:
frame2['pop']

# frame2.pop

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

> 行也可以通过位置或名称的方式进行获取，比如用loc属性（稍后将对此进行详细讲解）：

In [61]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

> 列可以通过赋值的方式进行修改。例如，我们可以给那个空的"debt"列赋上一个标量值或一组值：

In [62]:
frame2['debt'] = 16.5

frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [69]:
import numpy as np


frame2['debt'] = np.arange(6.)

frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

> 将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值：

In [71]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])


frame2['debt'] = val


frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

> 为不存在的列赋值会创建出一个新列。关键字del用于删除列。
> 
> 作为del的例子，我先添加一个新的布尔值的列，state是否为'Ohio'：

In [72]:
frame2['eastern'] = frame2.state == 'Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

> del方法可以用来删除这列：

In [75]:
# del frame2['eastern']

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [76]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

> 另一种常见的数据形式是嵌套字典：

In [82]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio':   {2000: 1.5, 2001: 1.7, 2002: 3.6}
      }

> 如果嵌套字典传给DataFrame，pandas就会被解释为：外层字典的键作为列，内层键则作为行索引：

In [84]:
frame3 = pd.DataFrame(pop)


frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

> 你也可以使用类似NumPy数组的方法，对DataFrame进行转置（交换行和列）：

In [79]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

> 内层字典的键会被合并、排序以形成最终的索引。如果明确指定了索引，则不会这样：

In [85]:
pd.DataFrame(pop, index=[2000, 2001, 2002, 2003])

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

> 由Series组成的字典差不多也是一样的用法：

In [87]:
frame3['Ohio']

2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [88]:
frame3['Nevada']

2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64

In [86]:
pdata = {'Ohio':   frame3['Ohio'][:-1], 
         'Nevada': frame3['Nevada'][:2]
        }

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

> 如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示出来：

In [91]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据：

In [92]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

如果DataFrame各列的数据类型不同，则值数组的dtype就会选用能兼容所有列的数据类型：

In [94]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

pandas的索引对象负责管理轴标签和其他元数据（比如轴名称等）。构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index：

In [105]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

obj.index

Index(['a', 'b', 'c'], dtype='object')

In [107]:
obj

a    0
b    1
c    2
dtype: int64

In [108]:
index = obj.index

index

Index(['a', 'b', 'c'], dtype='object')

In [109]:
obj

a    0
b    1
c    2
dtype: int64

不可变可以使Index对象在多个数据结构之间安全共享：

In [110]:
labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [112]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [113]:
obj2.index is labels

True

除了类似于数组，Index的功能也类似一个固定大小的集合：

In [114]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [115]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [116]:
'Ohio' in frame3.columns

True

In [117]:
2003 in frame3.index

False

与python的集合不同，pandas的Index可以包含重复的标签：

In [119]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

选择重复的标签，会显示所有的结果。

每个索引都有一些方法和属性，它们可用于设置逻辑并回答有关该索引所包含的数据的常见问题。表5-2列出了这些函数。