In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 一次模拟多个随机漫步

> 如果你希望模拟多个随机漫步过程（比如5000个），只需对上面的代码做一点点修改即可生成所有的随机漫步过程。只要给numpy.random的函数传入一个二元元组就可以产生一个二维数组，然后我们就可以一次性计算5000个随机漫步过程（一行一个）的累计和了：

In [3]:
nwalks = 5000
nsteps = 1000


draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1


steps = np.where(draws > 0, 1, -1)


walks = steps.cumsum(1)

In [12]:
print("行走步数记录: ")
steps

行走步数记录: 


array([[-1, -1, -1, ...,  1,  1,  1],
       [-1, -1,  1, ..., -1, -1, -1],
       [-1,  1,  1, ...,  1,  1, -1],
       ...,
       [ 1,  1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ..., -1,  1,  1],
       [ 1, -1,  1, ...,  1,  1,  1]])

In [13]:
print("每次行走, 距离起点路长: ")
walks

每次行走, 距离起点路长: 


array([[ -1,  -2,  -3, ..., -40, -39, -38],
       [ -1,  -2,  -1, ...,  32,  31,  30],
       [ -1,   0,   1, ...,  -8,  -7,  -8],
       ...,
       [  1,   2,   3, ...,  32,  33,  32],
       [  1,   2,   3, ..., -18, -17, -16],
       [  1,   0,   1, ..., -32, -31, -30]])

> 现在，我们来计算所有随机漫步过程的最大值和最小值：

In [14]:
print(walks.max())
print(walks.min())

118
-122


> 得到这些数据之后，我们来计算30或－30的最小穿越时间。这里稍微复杂些，因为不是5000个过程都到达了30。我们可以用any方法来对此进行检查：

In [17]:
hits30 = (np.abs(walks) >= 30).any(1)

hits30

array([ True,  True,  True, ...,  True, False,  True])

In [16]:
hits30.sum() # Number that hit 30 or -30

3358

> 然后我们利用这个布尔型数组选出那些穿越了30（绝对值）的随机漫步（行），并调用argmax在轴1上获取穿越时间：

In [18]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

crossing_times.mean()

502.15187611673616

> 请尝试用其他分布方式得到漫步数据。只需使用不同的随机数生成函数即可，如normal用于生成指定均值和标准差的正态分布数据：