In [7]:
import numpy as np


arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
# 元素级别的运算
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## 数组与标量的运算

In [9]:
1 / arr


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
print(arr)

arr ** 0.5

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## 基本的索引和切片

### 一维切片

In [15]:
arr = np.arange(10)
print(arr)

print(arr[5])

print(arr[1:5])

arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[1 2 3 4]
[ 0  1  2  3  4 12 12 12  8  9]


In [16]:
aList = [1,2,3,4,5]

bList = aList

bList[0] = 234

print(aList)

[234, 2, 3, 4, 5]
