# A.6 更多有关排序的话题

跟Python内置的列表一样，ndarray的sort实例方法也是就地排序。也就是说，数组内容的重新排列是不会产生新数组的：

In [2]:
import numpy as np

In [3]:
arr = np.random.randn(6)

arr.sort()

arr

array([-0.30826509, -0.20607945,  0.08027812,  1.10375238,  1.1800909 ,
        1.4999838 ])

在对数组进行就地排序时要注意一点，如果目标数组只是一个视图，则原始数组将会被修改：

In [4]:
arr = np.random.randn(3, 5)

arr

array([[-0.9506252 ,  0.03810191, -0.45741525, -0.21485722,  0.22785563],
       [ 0.21478368,  0.00725486, -0.66159205,  1.6715343 , -0.63847846],
       [-0.18868164, -0.51598031,  1.71909875,  1.36262638,  0.88090668]])

In [5]:
arr[:, 0].sort()  # Sort first column values in-place

In [7]:
# 很明显, 没有被修改
arr

array([[-0.9506252 ,  0.03810191, -0.45741525, -0.21485722,  0.22785563],
       [-0.18868164,  0.00725486, -0.66159205,  1.6715343 , -0.63847846],
       [ 0.21478368, -0.51598031,  1.71909875,  1.36262638,  0.88090668]])

相反，numpy.sort会为原数组创建一个已排序副本。另外，它所接受的参数（比如kind）跟ndarray.sort一样：

In [9]:
arr = np.random.randn(5)

arr

array([-0.40724733, -0.13473455,  2.46845716, -1.74959492, -0.36279067])

In [10]:
np.sort(arr)

array([-1.74959492, -0.40724733, -0.36279067, -0.13473455,  2.46845716])

In [11]:
arr

array([-0.40724733, -0.13473455,  2.46845716, -1.74959492, -0.36279067])